# -*- python -*-
#
# Copyright 2022 Stéphane Caron
#
# This file makes our directory a Bazel package, allowing for neighboring *.bzl
# files to be loaded.

load("//tools/lint:lint.bzl", "add_lint_tests")

add_lint_tests()
