# -*- python -*-
#
# Copyright 2023 Inria

load("@pip_vulp//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "python",
    srcs = [
        "__init__.py",
    ],
    deps = [
        "//vulp/spine:python",
        "//vulp/utils:python",
    ],
)
